---

- name: Converge boot node
  hosts: "*boot*"
  become: true
  vars:
    bc_haya_comp_state_wallet: present
    bc_haya_comp_state_boot: present
    bc_haya_comp_state_bench: present
    install_promstack: true
  roles:
    - role: tank.ansible-haya

- name: Converge producer node
  hosts: "*producer*"
  become: true
  vars:
    bc_haya_comp_state_prod: present
    bc_haya_comp_state_bench: present
    install_promstack: true
    bc_haya_node_id: "{{ play_hosts.index(inventory_hostname) | int +1 }}"
  roles:
    - role: tank.ansible-haya
