---
- name: "Setup promstack at {{ inventory_hostname }}"
  include_role:
    name: ansible-promstack
  vars:
    install_cadvisor: false
    install_gateway: false
    prometheus_targets: [{jobname: "node_exporter", host: "localhost", port: "{{ node_exporter_port}}"}]

- name: "Add prometheus targets to {{ inventory_hostname }}"
  loop: "{{ bc_peers_ip }}"
  template:
    src: "configs/prometheus/target.yml.j2"
    dest: "/etc/prometheus/targets/{{ target_ip }}.yml"
  vars:
    - target_ip: "{{ item }}"
    - target_ports: ["8080", "9100"]
  when: install_promstack == true