---
- name: Import datasource for grafana
  grafana_datasource:
    name: "monitoring"
    grafana_url: "http://localhost:3000"
    grafana_user: "{{ admin_user }}"
    grafana_password: "{{ admin_password }}"
    org_id: "1"
    ds_type: "prometheus"
    url: "http://localhost:9090"
