---
- src: https://github.com/geerlingguy/ansible-role-docker
  version: master
  name: geerlingguy.docker

- src: https://github.com/geerlingguy/ansible-role-pip
  version: master
  name: geerlingguy.pip

- src: https://github.com/cyber-os/ansible-promstack
  version: master
  name: ansible-promstack