---
# tasks file for ansible-cyberos

- name: "Install required packages"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ntp

- name: Login to docker registry
  include_tasks: "init.yml"

- name: Show debug variables
  include_tasks: "debug/show-state.yml"
  tags:
    - never
    - debug

- name: Login to docker registry
  include_tasks: "docker/registry.yml"

- name: "Setup docker network"
  include_tasks: "docker/network.yml"

- name: "Install blockchain components"
  include_tasks: "blockchain/{{ bc_name }}/main.yml"
  tags:
    - prod
    - resume
