---
# tasks file for ansible-cyberos

- name: Login to docker registry
  include_tasks: "docker/registry.yml"

- name: "Setup docker network"
  include_tasks: "docker/network.yml"

- name: "Install blockchain components"
  include_tasks: "blockchain/{{ bc_name }}/main.yml"
