---
# tasks file for ansible-cyberos

- name: Login to docker registry
  include_tasks: docker-registry.yml

- name: "Setup docker network"
  include_tasks: docker-network.yml

- name: Screate directory for cleos
  file:
    path: /opt/eosio/bin
    state: directory

- name: "Setup cleos"
  template:
    src: scripts/bin/cleos
    dest: /opt/eosio/bin/cleos
    mode: 0755

- name: Create general directory structure
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ pref_dir }}"
    - "{{ work_dir }}"
- name: "Setup wallet containers"
  include_tasks: wallet.yml
