---
- name: "Set component variables"
  set_fact:
    bc_component_name: "wallet"

- name: "Make directory structure"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bc_path_data }}"
    - "{{ bc_path_config }}"
    - "{{ bc_path_state }}"

- name: "Start {{ bc_name }} container"
  docker_container:
    name: "{{ bc_name }}-{{ bc_component_name }}"
    image: registry.gitlab.com/cyberos/infrastructure/cyberos:latest
    command: /opt/eosio/bin/keosd --unlock-timeout=99999999 --wallet-dir {{ bc_path_data }} --http-server-address=0.0.0.0:{{ wallet.port }} --http-alias=keosd:{{ wallet.port }} --http-alias=localhost:{{ wallet.port }}
    hostname: cyberos-keosd
    ports:
      - "{{ wallet.port }}:{{ wallet.port }}"
    expose:
      - "{{ wallet.port }}"
    volumes:
      - "{{ bc_path_data }}:{{ bc_path_data }}"
    capabilities:
      - IPC_LOCK
    stop_timeout: 600
    networks:
      - name: "{{ bc_name }}-net"

- name: Create default wallet
  shell:
    cmd: "/opt/eosio/bin/cleos --wallet-url=http://localhost:{{wallet.port}} wallet create --to-console"
  register: out_create_wallet
  failed_when: "'Wallet already exists' not in out_create_wallet.stderr and out_create_wallet.rc != 0"
  changed_when: "'Creating wallet' in out_create_wallet.stdout"

- debug:
    msg: "{{ out_create_wallet.stderr_lines }}"

- debug:
    msg: "{{ out_create_wallet.stdout_lines }}"
