---
- name: Collect facts
  hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Gathering Facts
      setup:

- name: Create groups
  hosts: localhost
  gather_facts: false
  vars:
    bc_private_interface: enp0s8
  tasks:
    - name: "Add boot node to group bcboot"
      add_host:
        name: "{{ item }}"
        groups: bcboot
        inventory_dir: "{{ hostvars[item].inventory_dir }}"
      loop: "{{ groups['all'] }}"
      when: '"boot" in hostvars[item]["ansible_hostname"]'
    - name: "Add all nodes to group bcpeers"
      add_host:
        name: "{{ item }}"
        groups: bcpeers
        inventory_dir: "{{ hostvars[item].inventory_dir }}"
      loop: "{{ groups['all'] }}"
      when: '"prod" in hostvars[item]["ansible_hostname"] or "boot" in hostvars[item]["ansible_hostname"]'
    - name: "Add monitnoring nodes to group monitoring_peer"
      register: _create_group_monitoring
      add_host:
        name: "{{ item }}"
        groups: monitoring_peer
        inventory_dir: "{{ hostvars[item].inventory_dir }}"
      loop: "{{ groups['all'] }}"
      when: '"monitoring" in hostvars[item]["ansible_hostname"]'

- name: Converge boot node
  hosts: "*boot*"
  become: true
  vars:
    bc_haya_comp_state_wallet: present
    bc_haya_comp_state_boot: present
    bc_haya_comp_state_bench: present
    install_promstack: true
    bc_haya_node_id: 0
    bc_haya_plugin_randpa: present
  roles:
    - role: tank.ansible-haya

- name: Converge producer node
  hosts: "*producer*"
  become: true
  vars:
    bc_haya_comp_state_prod: present
    bc_haya_comp_state_bench: present
    install_promstack: true
    bc_haya_node_id: "{{ play_hosts.index(inventory_hostname) | int }}"
    bc_haya_plugin_randpa: present
  roles:
    - role: tank.ansible-haya

- name: Converge monitoring node
  hosts: "*monitoring*"
  become: true
  vars:
    bc_haya_comp_state_monitoring: present
    install_promstack: true
    admin_user: tank
    admin_password: tank
  roles:
    - role: tank.ansible-haya
