---
- name: set producer account
  set_fact:
    producer_account: "{{ bc_haya_producer_accounts[bc_haya_node_id | int] }}"
  tags:
    - update

- debug:
    msg: "{{ bc_haya_node_id | int }}"
  tags:
    - never
    - prod
    - debug

- debug:
    msg: "{{ producer_account }}"
  tags:
    - never
    - prod
    - debug

- name: "Make directory structure"
  tags:
    - prod
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bc_path_data }}"
    - "{{ bc_path_config }}"
    - "{{ bc_path_state }}"

- name: set config.ini
  tags:
    - update
  vars:
    producer_name: "{{ producer_account.name }}"
    producer_pub_key: "{{ producer_account.pub_key }}"
    producer_pvt_key: "{{ producer_account.pvt_key }}"
  template:
    src: configs/nodeos/config.ini.j2
    dest: "{{ bc_path_config }}/config.ini"
  notify:
    - restart prodnode

- name: set genesis.json
  tags:
    - update
  template:
    src: configs/nodeos/genesis.json.j2
    dest: "{{ bc_path_config }}/genesis.json"
  notify:
    - restart prodnode

- name: set accounts.json
  tags:
    - update
  template:
    src: configs/nodeos/accounts.json.j2
    dest: "{{ bc_path_config }}/accounts.json"
  notify:
    - restart prodnode

- name: set logger.json
  tags:
    - update
  template:
    src: configs/nodeos/logger.json.j2
    dest: "{{ bc_path_config }}/logger.json"
  notify:
    - restart prodnode

- name: "Start {{ bc_name }}-{{ bc_component_name }} container"
  tags:
    - update
  register: "{{ bc_name }}_{{ bc_component_name }}"
  docker_container:
    name: "{{ bc_name }}-{{ bc_component_name }}"
    image: "{{ bc_haya_image }}"
    command: |
      /opt/haya/bin/haya-node
      --config-dir={{ bc_path_config }}
      --genesis-json={{ bc_path_config }}/genesis.json
      --logconf={{ bc_path_config }}/logger.json
    hostname: "{{ bc_name }}-{{ bc_component_name }}"
    network_mode: host
    volumes:
      - "{{ bc_path_state }}:/root/.local"
      - "{{ bc_path_config }}:{{ bc_path_config }}"
      - "/tmp/cores:/tmp/cores"
    capabilities:
      - IPC_LOCK
    stop_timeout: 600
    pull: true

- name: List data about prod container
  debug:
    var="{{ bc_name }}_{{ bc_component_name }}"
  tags:
    - never
    - debug

- name: "Resume producer"
  uri:
    url: "http://localhost:{{ bc_haya_node_http_port }}/v1/producer/resume"
    method: POST
    body_format: form-urlencoded
    status_code: 201
  register: producer_resume
  retries: 10
  delay: 5
  until: producer_resume is success
  tags:
    - update
