---
- name: "List target host ip address for {{ inventory_hostname }}"
  tags:
    - never
    - debug
    - network
  debug:
    msg: "{{ hostvars[inventory_hostname]['ansible_'+bc_private_interface]['ipv4']['address'] }}"

- name: "List peers ip addresses for {{ inventory_hostname }}"
  tags:
    - never
    - debug
    - network
  loop: "{{ bc_list_of_peers }}"
  debug:
    msg: "{{ item }}"
