---
- name: set producer account
  set_fact:
    producer_account: "{{ bc_cyberos_producer_accounts[bc_cyberos_node_id | int] }}"
  tags:
    - prod

- debug:
    msg: "{{ bc_cyberos_node_id | int }}"
  tags:
    - never
    - prod
    - debug

- debug:
    msg: "{{ producer_account }}"
  tags:
    - never
    - prod
    - debug

- name: "Make directory structure"
  tags:
    - prod
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bc_path_data }}"
    - "{{ bc_path_config }}"
    - "{{ bc_path_state }}"

- name: set config.ini
  tags:
    - prod
  vars:
    producer_name: "{{ producer_account.name }}"
    producer_pub_key: "{{ producer_account.pub_key }}"
    producer_pvt_key: "{{ producer_account.pvt_key }}"
  template:
    src: configs/nodeos/config.ini.j2
    dest: "{{ bc_path_config }}/config.ini"

- name: set genesis.json
  tags:
    - prod
  template:
    src: configs/nodeos/genesis.json.j2
    dest: "{{ bc_path_config }}/genesis.json"

- name: set accounts.json
  tags:
    - prod
  template:
    src: configs/nodeos/accounts.json.j2
    dest: "{{ bc_path_config }}/accounts.json"

- name: "Start {{ bc_name }}-{{ bc_component_name }} container"
  register: "{{ bc_name }}_{{ bc_component_name }}"
  docker_container:
    recreate: true
    name: "{{ bc_name }}-{{ bc_component_name }}"
    image: registry.gitlab.com/cyberos/infrastructure/cyberos:latest
    command: /opt/eosio/bin/nodeos --config-dir={{ bc_path_config }} --genesis-json={{ bc_path_config }}/genesis.json --delete-all-blocks
    hostname: "{{bc_name}}-{{ bc_component_name }}"
    ports:
      - 127.0.0.1:{{ bc_cyberos_node_http_port }}:8888
      - 127.0.0.1:{{ bc_cyberos_node_p2p_port }}:9876
      - 0.0.0.0:{{ bc_cyberos_node_bnet_port }}:4321
    volumes:
      - "{{ bc_path_state }}:/root/.local"
      - "{{ bc_path_config }}:{{ bc_path_config }}"
    capabilities:
      - IPC_LOCK
    stop_timeout: 600
    networks:
      - name: cyberos-net

- name: List data about prod container
  debug:
    var="{{ bc_name }}_{{ bc_component_name }}"
  tags:
    - never
    - debug

- name: "Resume producer"
  uri:
    url: "http://localhost:{{ bc_cyberos_node_http_port }}/v1/producer/resume"
    method: POST
    body_format: form-urlencoded
    status_code: 201
  register: producer_resume
  retries: 3
  delay: 5
  until: producer_resume is success
  tags:
    - resume
